/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaplane.Graphics;

import javax.swing.*;

import javaplane.Decorators.App;
import javaplane.Event.RepaintListener;

import java.awt.*;

//основна панель для малювання
public class AppCanvas extends JPanel {
    Boolean state = false;
    private LayerManager layerManager = null;//шари зображень
    private App app = null;//головний клас
    public AppCanvas(LayerManager lm, App app){
        this.app = app;
        layerManager = lm;
        //resize to bg image size
        Image bg = layerManager.background;
        setPreferredSize(new Dimension(bg.getWidth(null),bg.getHeight(null)));
        setBackground(Color.BLACK);
        setDoubleBuffered(true);
        setFocusable(true);
        requestFocus();
    }

    //перемальовуємо панель
    @Override
    protected void paintComponent(Graphics g){
        g.setColor(Color.red);
        // Perform your rendering operations on the off-screen buffer
        layerManager.paint(g);
        // шрифт для 7-сегментного дисплея
        g.setFont(new Font("Seven Segment", Font.PLAIN, 40));
        //call all repaint listeners of app
        for (RepaintListener listener : app.repaintListeners) {
            listener.repaintRequested(g);
        }
        g.dispose();
    }
}
